How it should look:
A single matrix should be a transmission line matrix of length 9mm. To the inductance of this matrix should be added the inducatanceof the discrete inductor. This should be multiplied by the matrix of a capacitor.

dimensions:
cell length 9 mm
capacitor length 0.5 mm
C_0 = 0.13616e-12 f/mm
L_0 = 0.23815e-9 h/mm


In [15]:
function tl_matrix(l, Z, omega)
    [cos(omega*l) im*Z*sin(omega*l) ; (im/Z)*sin(omega*l) cos(omega*l)];
end

function capacitor_matirx(C, omega)
    [1 -im*omega*C; 0 1];
end


capacitor_matirx (generic function with 1 method)

In [56]:
Length = 95;
dx = 0.05;
N = Int64(Length/dx);
result_matrix = zeros(ComplexF64, 2, N + 1) 
result_matrix[:, 1] = [1 ; 1/50]

C_0 = 0.136e-12; # farad/mm
L_0 = 0.238e-9; # henry/mm
d = 9; # mm
Z_0 = (L_0/C_0)^0.5; # ohm
C = 2.7e-12;
L = 2.8e-9;

L_tot_per_unit_length = (N*L + L_0); 

omega = 2*pi*0.2e8;
beta = omega *(L_tot_per_unit_length*C_0)^0.5;

for i = 0:9  # iterating over cells
     # buliding each cell
    for j = 1:Int64(9/dx) # the transmission line part
        result_matrix[:, (190)*i + j+1] = tl_matrix(dx,Z_0, beta)*result_matrix[:, 190*i + j];
    end

    for k = 1:Int64(0.5/dx) # the capcictor part
        result_matrix[:, 190*i + Int64(9/dx) + k + 1] = capacitor_matirx(C*(0.5/dx), omega)*result_matrix[:, 10*i + Int64(9/dx) + k];
    end
end



In [ ]:
plot(real(result_matrix[2,:]))

In [ ]:
plot(imag(result_matrix[2,:]))

In [ ]:
tl_result_mat = zeros(ComplexF64, 2, Int64(9/0.001));
tl_result_mat[:, 1] = [1 1/50];

for i = 2:length(tl_result_mat[1,:])
    tl_result_mat[:, i] = tl_matrix(0.001, Z_0, beta)*tl_result_mat[:, i-1];
end

In [ ]:
plot(real(tl_result_mat[1,:]))

In [ ]:
capacitor_matrix(C, omega) * [A ; B]

In [ ]:
function long_matrix(L_0, C_0, L, d, omega)
    [1 im*omega*L_0*d ; im*omega*C_0*d+1/(im*omega*L) 1];
end

function short_matrix(C, C_0, d, omega)
    [1 1/(im*omega*C); im*omega*C_0*d 1];
end


In [1]:
A = [ 2 2 3 5 6 7 4 3 0.4]

1×9 Matrix{Float64}:
 2.0  2.0  3.0  5.0  6.0  7.0  4.0  3.0  0.4

In [3]:
A[end]

0.4

In [11]:
LinRange(1, 8, 8)

8-element LinRange{Float64}:
 1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0

In [44]:
using Plots
k_vec = [];
theta_vec = [];
for ind in LinRange(3,8,100)
    theta = ind*pi*2e9;
    push!(theta_vec, theta/(2*pi));
    push!(k_vec,  (theta*((L_0 - 1/(C*d*theta^2))*(C_0 - 1/(L*d*theta^2)))^0.5));
end

plot(k_vec, theta_vec,

        xlabel = "wave number [mm]",
        ylabel = "frequency [Hz]",
        title = "Dispersion relation between the gaps" 
        )

savefig("graph.svg")




"/home/yotamktz1/Downloads/Uni/Year_d/77508_lab_3/meta_materials/graph.svg"

In [57]:
theta = pi*12e9;
c_vel = ((L_0 - 1/(C*d*theta^2))*(C_0 - 1/(L*d*theta^2)))^-0.5

2.10383078183209e11

In [59]:
187/2

93.5

Not code but a break

In [22]:
start_V_I = [1 1/50]';num_freqs = Int64(100)
N = Int64(10000)
two_dim_map = zeros(ComplexF64, num_freqs, N);
smarter_result_matrix = zeros(Complex{Float64},2,N);
start_V_I = [1 1/50]';

function initializing_omega(omega) 
    # this creates the ABCD matrix for a given omega
    #

    C_0 = 0.17e-12;
    L_0 = 0.238e-9; 
    d = 9;
    Z_0 = (L_0/C_0)^-0.5;

    L = 2.8e-9
    C = 2.7e-12

    
    
    series_matrix = [1 (im*L_0*d*omega - im/(omega*C)) ; 0 1];
    parallel_matrix = [1 0 ; (im*C_0*d*omega - im/(omega*L))  1];

    cell_matrix = (series_matrix*parallel_matrix);
    dx_matrix = cell_matrix^(1/(N/20));
    
    return dx_matrix
end;

In [23]:
A =  initializing_omega(4e9)

2×2 Matrix{ComplexF64}:
     1.00477+0.00631323im   -0.000722878+0.115048im
 -7.15488e-7+0.000113872im      0.995201+0.00625312im

In [20]:
A

2×2 Matrix{ComplexF64}:
    1.00477+0.00631323im   0.000722878-0.115048im
 7.15488e-7-0.000113872im     0.995201+0.00625312im